"""Pi0.5 CUDA kernel catalog registered through the devproc2 DSL."""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import devproc2.frontend.dsl as dp
from devproc2.kernel import KernelLaunchSpec, KernelParamSpec, KernelSpec


_CUDA_SOURCE = Path(__file__).resolve().parent / "cuda" / "pi05_kernels.cu"


@dataclass(frozen=True)
class Pi05KernelDecl:
    op: str
    fn_name: str
    symbol: str
    dtypes: tuple[str, ...]
    output_dtype: str | None
    params: tuple[KernelParamSpec, ...]
    launch: KernelLaunchSpec
    priority: int = 100


def _tensor_param(name: str, source: str, index: int) -> KernelParamSpec:
    return KernelParamSpec(name, "tensor", source=source, index=index)


def _scalar_param(name: str, dtype: str) -> KernelParamSpec:
    return KernelParamSpec(name, "scalar", dtype=dtype)


PI05_KERNELS: tuple[Pi05KernelDecl, ...] = (
    Pi05KernelDecl(
        op="pi05.image_u8_to_bf16_norm",
        fn_name="pi05_image_u8_to_bf16_norm",
        symbol="pi05_image_u8_to_bf16_norm",
        dtypes=("uint8",),
        output_dtype="bfloat16",
        params=(
            _tensor_param("image_u8", "input", 0),
            _scalar_param("n", "int64"),
            _tensor_param("out_bf16", "output", 0),
        ),
        launch=KernelLaunchSpec(grid=(1, 1, 1), block=(256, 1, 1)),
    ),
    Pi05KernelDecl(
        op="pi05.cast_f32_to_bf16",
        fn_name="pi05_cast_f32_to_bf16",
        symbol="pi05_cast_f32_to_bf16",
        dtypes=("float32", ""),
        output_dtype="bfloat16",
        params=(
            _tensor_param("x", "input", 0),
            _scalar_param("n", "int64"),
            _tensor_param("out_bf16", "output", 0),
        ),
        launch=KernelLaunchSpec(grid=(1, 1, 1), block=(256, 1, 1)),
    ),
    Pi05KernelDecl(
        op="pi05.embedding_gather_bf16",
        fn_name="pi05_embedding_gather_bf16",
        symbol="pi05_embedding_gather_bf16",
        dtypes=("int32", "bfloat16"),
        output_dtype="bfloat16",
        params=(
            _tensor_param("token_ids", "input", 0),
            _tensor_param("embedding", "input", 1),
            _scalar_param("num_tokens", "int64"),
            _scalar_param("hidden", "int64"),
            _tensor_param("out", "output", 0),
        ),
        launch=KernelLaunchSpec(grid=(1, 1, 1), block=(256, 1, 1)),
    ),
    Pi05KernelDecl(
        op="pi05.patch_im2col_bf16",
        fn_name="pi05_patch_im2col_bf16",
        symbol="pi05_patch_im2col_bf16",
        dtypes=("bfloat16", ""),
        output_dtype="bfloat16",
        params=(
            _tensor_param("image", "input", 0),
            _scalar_param("num_views", "int64"),
            _tensor_param("patches", "output", 0),
        ),
        launch=KernelLaunchSpec(grid=(1, 1, 1), block=(256, 1, 1)),
    ),
    Pi05KernelDecl(
        op="pi05.rope_qwen3_bf16",
        fn_name="pi05_rope_qwen3_bf16",
        symbol="pi05_rope_qwen3_bf16",
        dtypes=("bfloat16", "bfloat16", "bfloat16"),
        output_dtype=None,
        params=(
            _tensor_param("x", "input", 0),
            _tensor_param("cos", "input", 1),
            _tensor_param("sin", "input", 2),
            _scalar_param("S", "int64"),
            _scalar_param("NH", "int64"),
            _scalar_param("HD", "int64"),
        ),
        launch=KernelLaunchSpec(grid=(1, 1, 1), block=(256, 1, 1)),
    ),
    Pi05KernelDecl(
        op="pi05.qkv_split_bf16",
        fn_name="pi05_qkv_split_bf16",
        symbol="pi05_qkv_split_bf16",
        dtypes=("bfloat16", "", "", "", ""),
        output_dtype=None,
        params=(
            _tensor_param("qkv", "input", 0),
            _scalar_param("rows", "int64"),
            _scalar_param("q_dim", "int64"),
            _scalar_param("k_dim", "int64"),
            _scalar_param("v_dim", "int64"),
            _tensor_param("q", "output", 0),
            _tensor_param("k", "output", 1),
            _tensor_param("v", "output", 2),
        ),
        launch=KernelLaunchSpec(grid=(1, 1, 1), block=(256, 1, 1)),
    ),
    Pi05KernelDecl(
        op="pi05.qkv_bias_split_bf16",
        fn_name="pi05_qkv_bias_split_bf16",
        symbol="pi05_qkv_bias_split_bf16",
        dtypes=("bfloat16", "bfloat16", "", "", "", ""),
        output_dtype=None,
        params=(
            _tensor_param("qkv", "input", 0),
            _tensor_param("bias", "input", 1),
            _scalar_param("rows", "int64"),
            _scalar_param("q_dim", "int64"),
            _scalar_param("k_dim", "int64"),
            _scalar_param("v_dim", "int64"),
            _tensor_param("q", "output", 0),
            _tensor_param("k", "output", 1),
            _tensor_param("v", "output", 2),
        ),
        launch=KernelLaunchSpec(grid=(1, 1, 1), block=(256, 1, 1)),
    ),
    Pi05KernelDecl(
        op="pi05.qkv_split_rope_bf16",
        fn_name="pi05_qkv_split_rope_bf16",
        symbol="pi05_qkv_split_rope_bf16",
        dtypes=("bfloat16", "bfloat16", "", "", "", "", ""),
        output_dtype=None,
        params=(
            _tensor_param("qkv", "input", 0),
            _tensor_param("rope_interleaved", "input", 1),
            _scalar_param("rows", "int64"),
            _scalar_param("q_dim", "int64"),
            _scalar_param("k_dim", "int64"),
            _scalar_param("v_dim", "int64"),
            _scalar_param("head_dim", "int64"),
            _tensor_param("q", "output", 0),
            _tensor_param("k", "output", 1),
            _tensor_param("v", "output", 2),
        ),
        launch=KernelLaunchSpec(grid=(1, 1, 1), block=(256, 1, 1)),
    ),
    Pi05KernelDecl(
        op="pi05.qkv_split_rope_cache_bf16",
        fn_name="pi05_qkv_split_rope_cache_bf16",
        symbol="pi05_qkv_split_rope_cache_bf16",
        dtypes=("bfloat16", "bfloat16", "bfloat16", "bfloat16", "", "", "", "", "", "", ""),
        output_dtype="bfloat16",
        params=(
            _tensor_param("qkv", "input", 0),
            _tensor_param("rope_interleaved", "input", 1),
            _tensor_param("k_cache", "input", 2),
            _tensor_param("v_cache", "input", 3),
            _scalar_param("layer", "int64"),
            _scalar_param("rows", "int64"),
            _scalar_param("cache_rows", "int64"),
            _scalar_param("q_dim", "int64"),
            _scalar_param("k_dim", "int64"),
            _scalar_param("v_dim", "int64"),
            _scalar_param("head_dim", "int64"),
            _tensor_param("q", "output", 0),
        ),
        launch=KernelLaunchSpec(grid=(1, 1, 1), block=(256, 1, 1)),
    ),
    Pi05KernelDecl(
        op="pi05.qkv_split_rope_concat_bf16",
        fn_name="pi05_qkv_split_rope_concat_bf16",
        symbol="pi05_qkv_split_rope_concat_bf16",
        dtypes=("bfloat16", "bfloat16", "bfloat16", "bfloat16", "", "", "", "", "", ""),
        output_dtype="bfloat16",
        params=(
            _tensor_param("qkv", "input", 0),
            _tensor_param("rope_interleaved", "input", 1),
            _tensor_param("prefix_k", "input", 2),
            _tensor_param("prefix_v", "input", 3),
            _scalar_param("prefix_rows", "int64"),
            _scalar_param("suffix_rows", "int64"),
            _scalar_param("q_dim", "int64"),
            _scalar_param("k_dim", "int64"),
            _scalar_param("v_dim", "int64"),
            _scalar_param("head_dim", "int64"),
            _tensor_param("q", "output", 0),
            _tensor_param("out_k", "output", 1),
            _tensor_param("out_v", "output", 2),
        ),
        launch=KernelLaunchSpec(grid=(1, 1, 1), block=(256, 1, 1)),
    ),
    Pi05KernelDecl(
        op="pi05.kv_concat_bf16",
        fn_name="pi05_kv_concat_bf16",
        symbol="pi05_kv_concat_bf16",
        dtypes=("bfloat16", "bfloat16", "bfloat16", "bfloat16", "", "", "", ""),
        output_dtype=None,
        params=(
            _tensor_param("prefix_k", "input", 0),
            _tensor_param("prefix_v", "input", 1),
            _tensor_param("suffix_k", "input", 2),
            _tensor_param("suffix_v", "input", 3),
            _scalar_param("prefix_rows", "int64"),
            _scalar_param("suffix_rows", "int64"),
            _scalar_param("num_kv_heads", "int64"),
            _scalar_param("head_dim", "int64"),
            _tensor_param("out_k", "output", 0),
            _tensor_param("out_v", "output", 1),
        ),
        launch=KernelLaunchSpec(grid=(1, 1, 1), block=(256, 1, 1)),
    ),
    Pi05KernelDecl(
        op="pi05.copy_kv_cache_layer_bf16",
        fn_name="pi05_copy_kv_cache_layer_bf16",
        symbol="pi05_copy_kv_cache_layer_bf16",
        dtypes=("bfloat16", "bfloat16", "bfloat16", "bfloat16", "", "", ""),
        output_dtype=None,
        params=(
            _tensor_param("k", "input", 0),
            _tensor_param("v", "input", 1),
            _tensor_param("k_cache", "input", 2),
            _tensor_param("v_cache", "input", 3),
            _scalar_param("layer", "int64"),
            _scalar_param("rows", "int64"),
            _scalar_param("kv_dim", "int64"),
        ),
        launch=KernelLaunchSpec(grid=(1, 1, 1), block=(256, 1, 1)),
    ),
    Pi05KernelDecl(
        op="pi05.layer_norm_bf16",
        fn_name="pi05_layer_norm_bf16",
        symbol="pi05_layer_norm_bf16",
        dtypes=("bfloat16", "bfloat16", "bfloat16", "", "", ""),
        output_dtype="bfloat16",
        params=(
            _tensor_param("x", "input", 0),
            _tensor_param("weight", "input", 1),
            _tensor_param("bias", "input", 2),
            _scalar_param("rows", "int64"),
            _scalar_param("cols", "int64"),
            _scalar_param("eps_bits", "int64"),
            _tensor_param("out", "output", 0),
        ),
        launch=KernelLaunchSpec(grid=(1, 1, 1), block=(256, 1, 1)),
    ),
    Pi05KernelDecl(
        op="pi05.layer_norm_to_fp8_bf16",
        fn_name="pi05_layer_norm_to_fp8_bf16",
        symbol="pi05_layer_norm_to_fp8_bf16",
        dtypes=("bfloat16", "bfloat16", "bfloat16", "float32", "", "", ""),
        output_dtype="fp8_e4m3",
        params=(
            _tensor_param("x", "input", 0),
            _tensor_param("weight", "input", 1),
            _tensor_param("bias", "input", 2),
            _tensor_param("scale", "input", 3),
            _scalar_param("rows", "int64"),
            _scalar_param("cols", "int64"),
            _scalar_param("eps_bits", "int64"),
            _tensor_param("out_fp8", "output", 0),
        ),
        launch=KernelLaunchSpec(grid=(1, 1, 1), block=(256, 1, 1)),
    ),
    Pi05KernelDecl(
        op="pi05.rms_norm_bf16",
        fn_name="pi05_rms_norm_bf16",
        symbol="pi05_rms_norm_bf16",
        dtypes=("bfloat16", "bfloat16", "", "", ""),
        output_dtype="bfloat16",
        params=(
            _tensor_param("x", "input", 0),
            _tensor_param("weight", "input", 1),
            _scalar_param("rows", "int64"),
            _scalar_param("cols", "int64"),
            _scalar_param("eps_bits", "int64"),
            _tensor_param("out", "output", 0),
        ),
        launch=KernelLaunchSpec(grid=(1, 1, 1), block=(256, 1, 1)),
    ),
    Pi05KernelDecl(
        op="pi05.rms_norm_unit_bf16",
        fn_name="pi05_rms_norm_unit_bf16",
        symbol="pi05_rms_norm_unit_bf16",
        dtypes=("bfloat16", "", "", ""),
        output_dtype="bfloat16",
        params=(
            _tensor_param("x", "input", 0),
            _scalar_param("rows", "int64"),
            _scalar_param("cols", "int64"),
            _scalar_param("eps_bits", "int64"),
            _tensor_param("out", "output", 0),
        ),
        launch=KernelLaunchSpec(grid=(1, 1, 1), block=(256, 1, 1)),
    ),
    Pi05KernelDecl(
        op="pi05.rms_norm_unit_to_fp8_bf16",
        fn_name="pi05_rms_norm_unit_to_fp8_bf16",
        symbol="pi05_rms_norm_unit_to_fp8_bf16",
        dtypes=("bfloat16", "float32", "", "", ""),
        output_dtype="fp8_e4m3",
        params=(
            _tensor_param("x", "input", 0),
            _tensor_param("scale", "input", 1),
            _scalar_param("rows", "int64"),
            _scalar_param("cols", "int64"),
            _scalar_param("eps_bits", "int64"),
            _tensor_param("out_fp8", "output", 0),
        ),
        launch=KernelLaunchSpec(grid=(1, 1, 1), block=(256, 1, 1)),
    ),
    Pi05KernelDecl(
        op="pi05.rms_norm_to_fp8_bf16",
        fn_name="pi05_rms_norm_to_fp8_bf16",
        symbol="pi05_rms_norm_to_fp8_bf16",
        dtypes=("bfloat16", "bfloat16", "float32"),
        output_dtype="fp8_e4m3",
        params=(
            _tensor_param("x", "input", 0),
            _tensor_param("weight", "input", 1),
            _tensor_param("scale", "input", 2),
            _scalar_param("rows", "int64"),
            _scalar_param("cols", "int64"),
            _scalar_param("eps_bits", "int64"),
            _tensor_param("out_fp8", "output", 0),
        ),
        launch=KernelLaunchSpec(grid=(1, 1, 1), block=(256, 1, 1)),
    ),
    Pi05KernelDecl(
        op="pi05.residual_rms_norm_to_fp8_bf16",
        fn_name="pi05_residual_rms_norm_to_fp8_bf16",
        symbol="pi05_residual_rms_norm_to_fp8_bf16",
        dtypes=("bfloat16", "bfloat16", "bfloat16", "float32"),
        output_dtype="fp8_e4m3",
        params=(
            _tensor_param("residual", "input", 0),
            _tensor_param("addend", "input", 1),
            _tensor_param("weight", "input", 2),
            _tensor_param("scale", "input", 3),
            _scalar_param("rows", "int64"),
            _scalar_param("cols", "int64"),
            _scalar_param("eps_bits", "int64"),
            _tensor_param("out_fp8", "output", 0),
        ),
        launch=KernelLaunchSpec(grid=(1, 1, 1), block=(256, 1, 1)),
    ),
    Pi05KernelDecl(
        op="pi05.bias_residual_bf16",
        fn_name="pi05_bias_residual_bf16",
        symbol="pi05_bias_residual_bf16",
        dtypes=("bfloat16", "bfloat16", "bfloat16", "", ""),
        output_dtype=None,
        params=(
            _tensor_param("residual", "input", 0),
            _tensor_param("x", "input", 1),
            _tensor_param("bias", "input", 2),
            _scalar_param("rows", "int64"),
            _scalar_param("cols", "int64"),
        ),
        launch=KernelLaunchSpec(grid=(1, 1, 1), block=(256, 1, 1)),
    ),
    Pi05KernelDecl(
        op="pi05.bias_add_bf16",
        fn_name="pi05_bias_add_bf16",
        symbol="pi05_bias_add_bf16",
        dtypes=("bfloat16", "bfloat16", "", ""),
        output_dtype=None,
        params=(
            _tensor_param("x", "input", 0),
            _tensor_param("bias", "input", 1),
            _scalar_param("rows", "int64"),
            _scalar_param("cols", "int64"),
        ),
        launch=KernelLaunchSpec(grid=(1, 1, 1), block=(256, 1, 1)),
    ),
    Pi05KernelDecl(
        op="pi05.position_add_bf16",
        fn_name="pi05_position_add_bf16",
        symbol="pi05_position_add_bf16",
        dtypes=("bfloat16", "bfloat16", "", "", ""),
        output_dtype=None,
        params=(
            _tensor_param("x", "input", 0),
            _tensor_param("position", "input", 1),
            _scalar_param("rows", "int64"),
            _scalar_param("positions", "int64"),
            _scalar_param("cols", "int64"),
        ),
        launch=KernelLaunchSpec(grid=(1, 1, 1), block=(256, 1, 1)),
    ),
    Pi05KernelDecl(
        op="pi05.prefix_concat_bf16",
        fn_name="pi05_prefix_concat_bf16",
        symbol="pi05_prefix_concat_bf16",
        dtypes=("bfloat16", "bfloat16", "", "", ""),
        output_dtype="bfloat16",
        params=(
            _tensor_param("image_embs", "input", 0),
            _tensor_param("lang_embs", "input", 1),
            _scalar_param("image_rows", "int64"),
            _scalar_param("lang_rows", "int64"),
            _scalar_param("hidden", "int64"),
            _tensor_param("out", "output", 0),
        ),
        launch=KernelLaunchSpec(grid=(1, 1, 1), block=(256, 1, 1)),
    ),
    Pi05KernelDecl(
        op="pi05.residual_add_bf16",
        fn_name="pi05_residual_add_bf16",
        symbol="pi05_residual_add_bf16",
        dtypes=("bfloat16", "bfloat16", ""),
        output_dtype=None,
        params=(
            _tensor_param("residual", "input", 0),
            _tensor_param("x", "input", 1),
            _scalar_param("n", "int64"),
        ),
        launch=KernelLaunchSpec(grid=(1, 1, 1), block=(256, 1, 1)),
    ),
    Pi05KernelDecl(
        op="pi05.gate_mul_residual_bf16",
        fn_name="pi05_gate_mul_residual_bf16",
        symbol="pi05_gate_mul_residual_bf16",
        dtypes=("bfloat16", "bfloat16", "bfloat16", ""),
        output_dtype=None,
        params=(
            _tensor_param("residual", "input", 0),
            _tensor_param("x", "input", 1),
            _tensor_param("gate", "input", 2),
            _scalar_param("n", "int64"),
        ),
        launch=KernelLaunchSpec(grid=(1, 1, 1), block=(256, 1, 1)),
    ),
    Pi05KernelDecl(
        op="pi05.geglu_to_fp8_bf16",
        fn_name="pi05_geglu_to_fp8_bf16",
        symbol="pi05_geglu_to_fp8_bf16",
        dtypes=("bfloat16", "float32"),
        output_dtype="fp8_e4m3",
        params=(
            _tensor_param("merged_gate_up", "input", 0),
            _tensor_param("scale", "input", 1),
            _scalar_param("rows", "int64"),
            _scalar_param("hidden", "int64"),
            _tensor_param("out_fp8", "output", 0),
        ),
        launch=KernelLaunchSpec(grid=(1, 1, 1), block=(256, 1, 1)),
    ),
    Pi05KernelDecl(
        op="pi05.geglu_bf16",
        fn_name="pi05_geglu_bf16",
        symbol="pi05_geglu_bf16",
        dtypes=("bfloat16", "", ""),
        output_dtype="bfloat16",
        params=(
            _tensor_param("merged_gate_up", "input", 0),
            _scalar_param("rows", "int64"),
            _scalar_param("hidden", "int64"),
            _tensor_param("out", "output", 0),
        ),
        launch=KernelLaunchSpec(grid=(1, 1, 1), block=(256, 1, 1)),
    ),
    Pi05KernelDecl(
        op="pi05.gelu_inplace_bf16",
        fn_name="pi05_gelu_inplace_bf16",
        symbol="pi05_gelu_inplace_bf16",
        dtypes=("bfloat16", ""),
        output_dtype=None,
        params=(
            _tensor_param("x", "input", 0),
            _scalar_param("n", "int64"),
        ),
        launch=KernelLaunchSpec(grid=(1, 1, 1), block=(256, 1, 1)),
    ),
    Pi05KernelDecl(
        op="pi05.bias_gelu_to_fp8_bf16",
        fn_name="pi05_bias_gelu_to_fp8_bf16",
        symbol="pi05_bias_gelu_to_fp8_bf16",
        dtypes=("bfloat16", "bfloat16", "float32", "", ""),
        output_dtype="fp8_e4m3",
        params=(
            _tensor_param("x", "input", 0),
            _tensor_param("bias", "input", 1),
            _tensor_param("scale", "input", 2),
            _scalar_param("rows", "int64"),
            _scalar_param("cols", "int64"),
            _tensor_param("out_fp8", "output", 0),
        ),
        launch=KernelLaunchSpec(grid=(1, 1, 1), block=(256, 1, 1)),
    ),
    Pi05KernelDecl(
        op="pi05.ada_rms_norm_style_bf16",
        fn_name="pi05_ada_rms_norm_style_bf16",
        symbol="pi05_ada_rms_norm_style_bf16",
        dtypes=("bfloat16", "bfloat16", "bfloat16", "", "", ""),
        output_dtype=None,
        params=(
            _tensor_param("x", "input", 0),
            _tensor_param("weight", "input", 1),
            _tensor_param("style", "input", 2),
            _scalar_param("rows", "int64"),
            _scalar_param("cols", "int64"),
            _scalar_param("eps_bits", "int64"),
            _tensor_param("out", "output", 0),
            _tensor_param("gate_out", "output", 1),
        ),
        launch=KernelLaunchSpec(grid=(1, 1, 1), block=(256, 1, 1)),
    ),
    Pi05KernelDecl(
        op="pi05.ada_rms_norm_style_to_fp8_bf16",
        fn_name="pi05_ada_rms_norm_style_to_fp8_bf16",
        symbol="pi05_ada_rms_norm_style_to_fp8_bf16",
        dtypes=("bfloat16", "bfloat16", "bfloat16", "float32", "", "", ""),
        output_dtype=None,
        params=(
            _tensor_param("x", "input", 0),
            _tensor_param("weight", "input", 1),
            _tensor_param("style", "input", 2),
            _tensor_param("scale", "input", 3),
            _scalar_param("rows", "int64"),
            _scalar_param("cols", "int64"),
            _scalar_param("eps_bits", "int64"),
            _tensor_param("out_fp8", "output", 0),
            _tensor_param("gate_out", "output", 1),
        ),
        launch=KernelLaunchSpec(grid=(1, 1, 1), block=(256, 1, 1)),
    ),
    Pi05KernelDecl(
        op="pi05.gate_residual_ada_norm_to_fp8_bf16",
        fn_name="pi05_gate_residual_ada_norm_to_fp8_bf16",
        symbol="pi05_gate_residual_ada_norm_to_fp8_bf16",
        dtypes=("bfloat16", "bfloat16", "bfloat16", "bfloat16", "bfloat16", "float32", "", "", ""),
        output_dtype=None,
        params=(
            _tensor_param("residual", "input", 0),
            _tensor_param("x", "input", 1),
            _tensor_param("gate", "input", 2),
            _tensor_param("weight", "input", 3),
            _tensor_param("style", "input", 4),
            _tensor_param("scale", "input", 5),
            _scalar_param("rows", "int64"),
            _scalar_param("cols", "int64"),
            _scalar_param("eps_bits", "int64"),
            _tensor_param("out_fp8", "output", 0),
            _tensor_param("gate_out", "output", 1),
        ),
        launch=KernelLaunchSpec(grid=(1, 1, 1), block=(256, 1, 1)),
    ),
    Pi05KernelDecl(
        op="pi05.quantize_fp8_static_bf16",
        fn_name="pi05_quantize_fp8_static_bf16",
        symbol="pi05_quantize_fp8_static_bf16",
        dtypes=("bfloat16", "float32", ""),
        output_dtype="fp8_e4m3",
        params=(
            _tensor_param("x", "input", 0),
            _tensor_param("scale", "input", 1),
            _scalar_param("n", "int64"),
            _tensor_param("out_fp8", "output", 0),
        ),
        launch=KernelLaunchSpec(grid=(1, 1, 1), block=(256, 1, 1)),
    ),
    Pi05KernelDecl(
        op="pi05.quantize_fp8_dynamic_bf16",
        fn_name="pi05_quantize_fp8_dynamic_bf16",
        symbol="pi05_quantize_fp8_dynamic_bf16",
        dtypes=("bfloat16", ""),
        output_dtype=None,
        params=(
            _tensor_param("x", "input", 0),
            _scalar_param("n", "int64"),
            _tensor_param("out_fp8", "output", 0),
            _tensor_param("scale_out", "output", 1),
        ),
        launch=KernelLaunchSpec(grid=(1, 1, 1), block=(256, 1, 1)),
    ),
    Pi05KernelDecl(
        op="pi05.reduce_amax_bf16",
        fn_name="pi05_reduce_amax_bf16",
        symbol="pi05_reduce_amax_bf16",
        dtypes=("bfloat16", ""),
        output_dtype="float32",
        params=(
            _tensor_param("x", "input", 0),
            _scalar_param("n", "int64"),
            _tensor_param("partial_amax", "output", 0),
        ),
        launch=KernelLaunchSpec(grid=(1, 1, 1), block=(256, 1, 1)),
    ),
    Pi05KernelDecl(
        op="pi05.amax_to_scale",
        fn_name="pi05_amax_to_scale",
        symbol="pi05_amax_to_scale",
        dtypes=("float32", ""),
        output_dtype="float32",
        params=(
            _tensor_param("partial_amax", "input", 0),
            _scalar_param("n", "int64"),
            _tensor_param("scale_out", "output", 0),
        ),
        launch=KernelLaunchSpec(grid=(1, 1, 1), block=(256, 1, 1)),
    ),
    Pi05KernelDecl(
        op="pi05.attention_bf16",
        fn_name="pi05_attention_bf16",
        symbol="pi05_attention_bf16",
        dtypes=("bfloat16", "bfloat16", "bfloat16", "", "", "", "", "", ""),
        output_dtype="bfloat16",
        params=(
            _tensor_param("q", "input", 0),
            _tensor_param("k", "input", 1),
            _tensor_param("v", "input", 2),
            _scalar_param("rows_q", "int64"),
            _scalar_param("rows_k", "int64"),
            _scalar_param("num_q_heads", "int64"),
            _scalar_param("num_kv_heads", "int64"),
            _scalar_param("head_dim", "int64"),
            _scalar_param("scale_bits", "int64"),
            _tensor_param("out", "output", 0),
        ),
        launch=KernelLaunchSpec(grid=(1, 1, 1), block=(256, 1, 1)),
    ),
    Pi05KernelDecl(
        op="pi05.attention_prefix_bf16",
        fn_name="pi05_attention_prefix_bf16",
        symbol="pi05_attention_prefix_bf16",
        dtypes=("bfloat16", "bfloat16", "bfloat16", "", "", "", "", "", "", ""),
        output_dtype="bfloat16",
        params=(
            _tensor_param("q", "input", 0),
            _tensor_param("k", "input", 1),
            _tensor_param("v", "input", 2),
            _scalar_param("rows_q", "int64"),
            _scalar_param("prefix_rows", "int64"),
            _scalar_param("suffix_rows", "int64"),
            _scalar_param("num_q_heads", "int64"),
            _scalar_param("num_kv_heads", "int64"),
            _scalar_param("head_dim", "int64"),
            _scalar_param("scale_bits", "int64"),
            _tensor_param("out", "output", 0),
        ),
        launch=KernelLaunchSpec(grid=(1, 1, 1), block=(256, 1, 1)),
    ),
    Pi05KernelDecl(
        op="pi05.encoder_ffn_fp8_fused",
        fn_name="pi05_encoder_ffn_fp8_fused",
        symbol="pi05_encoder_ffn_fp8_fused",
        dtypes=(
            "bfloat16",
            "fp8_e4m3",
            "float32",
            "fp8_e4m3",
            "float32",
            "float32",
            "float32",
            "",
            "",
            "",
        ),
        output_dtype="bfloat16",
        params=(
            _tensor_param("x", "input", 0),
            _tensor_param("gate_up_w_fp8", "input", 1),
            _tensor_param("gate_up_w_scale", "input", 2),
            _tensor_param("down_w_fp8", "input", 3),
            _tensor_param("down_w_scale", "input", 4),
            _tensor_param("act0_scale", "input", 5),
            _tensor_param("act1_scale", "input", 6),
            _scalar_param("rows", "int64"),
            _scalar_param("hidden", "int64"),
            _scalar_param("intermediate", "int64"),
            _tensor_param("out", "output", 0),
        ),
        launch=KernelLaunchSpec(grid=(1, 1, 1), block=(256, 1, 1)),
        priority=10,
    ),
    Pi05KernelDecl(
        op="pi05.euler_update_f32",
        fn_name="pi05_euler_update_f32",
        symbol="pi05_euler_update_f32",
        dtypes=("float32", "float32"),
        output_dtype=None,
        params=(
            _tensor_param("x", "input", 0),
            _tensor_param("v", "input", 1),
            _scalar_param("dt_bits", "int64"),
            _scalar_param("n", "int64"),
        ),
        launch=KernelLaunchSpec(grid=(1, 1, 1), block=(256, 1, 1)),
    ),
    Pi05KernelDecl(
        op="pi05.euler_update_bf16",
        fn_name="pi05_euler_update_bf16",
        symbol="pi05_euler_update_bf16",
        dtypes=("float32", "bfloat16", "", ""),
        output_dtype=None,
        params=(
            _tensor_param("x", "input", 0),
            _tensor_param("v", "input", 1),
            _scalar_param("dt_bits", "int64"),
            _scalar_param("n", "int64"),
        ),
        launch=KernelLaunchSpec(grid=(1, 1, 1), block=(256, 1, 1)),
    ),
)


def pi05_kernel_specs(*, sm_arch: int = 89, source_path: str | None = None) -> tuple[KernelSpec, ...]:
    """Return concrete CUDA KernelSpecs for the Pi0.5 kernel catalog."""

    src = str(source_path or _CUDA_SOURCE)
    specs: list[KernelSpec] = []
    for decl in PI05_KERNELS:
        specs.append(
            KernelSpec(
                op_name=decl.op,
                device="cuda",
                input_dtypes=decl.dtypes,
                kernel_name=f"kernel.{decl.fn_name}",
                backend="cuda",
                output_dtype=decl.output_dtype,
                symbol=decl.symbol,
                sm_arches=(sm_arch,),
                priority=decl.priority,
                launch=decl.launch,
                params=decl.params,
                source_path=src,
                extra_nvcc_flags=("--std=c++17",),
            )
        )
    return tuple(specs)


def register_pi05_kernels(*, sm_arch: int = 89, source_path: str | None = None) -> None:
    """Register the Pi0.5 CUDA kernel catalog in the global DSL registry."""

    specs = pi05_kernel_specs(sm_arch=sm_arch, source_path=source_path)
    for decl, spec in zip(PI05_KERNELS, specs):
        decorator = dp.kernel(
            op=decl.op,
            backend=spec.backend,
            device=spec.device,
            dtypes=spec.input_dtypes,
            output_dtype=spec.output_dtype,
            symbol=spec.symbol,
            sm_arches=spec.sm_arches,
            priority=spec.priority,
            source_path=spec.source_path,
            params=spec.params,
            launch=spec.launch,
            extra_nvcc_flags=spec.extra_nvcc_flags,
        )

        def _stub(*args, _name=decl.fn_name):
            raise RuntimeError(f"{_name} is a compile-time kernel declaration")

        _stub.__name__ = decl.fn_name
        decorator(_stub)
